#define _NBL_GLSL_EXT_BLUR_OUTPUT_SET_DEFINED_ 0
#define _NBL_GLSL_EXT_BLUR_OUTPUT_BINDING_DEFINED_ 1

layout (set = _NBL_GLSL_EXT_BLUR_OUTPUT_SET_DEFINED_, binding = _NBL_GLSL_EXT_BLUR_OUTPUT_BINDING_DEFINED_, rgba16f) uniform image2D out_image;
#define _NBL_GLSL_EXT_BLUR_OUTPUT_DESCRIPTOR_DEFINED_

void nbl_glsl_ext_Blur_setData(in uvec3 coordinate, in uint channel, in float val)
{
	const ivec2 image_dims = imageSize(out_image);
	if (all(lessThan(coordinate.xy, image_dims)))
	{
		vec4 color = imageLoad(out_image, ivec2(coordinate.xy));
		color[channel] = val;
		imageStore(out_image, ivec2(coordinate.xy), color);
	}
}

#define _NBL_GLSL_EXT_BLUR_SET_DATA_DEFINED_

#include "nbl/builtin/glsl/ext/CentralLimitBoxBlur/default_compute_blur.comp"