#version 430 core
layout(local_size_x=256, local_size_y=1, local_size_z=1) in;
 
#include <nbl/builtin/glsl/math/complex.glsl>

layout(set=0, binding=0) restrict readonly buffer InBuffer
{
	nbl_glsl_complex in_data[];
};

layout(set=0, binding=1) restrict buffer OutBuffer
{
	nbl_glsl_complex out_data[];
};

void main()
{
	float power = length(in_data[0]);
	vec2 normalized_data = in_data[gl_GlobalInvocationID.x]/power;
	out_data[gl_GlobalInvocationID.x] = normalized_data;
}