#define _NBL_V_IN_POSITION_ATTRIBUTE_ID 0
#define _NBL_V_IN_NORMAL_ATTRIBUTE_ID 1
#define _NBL_V_IN_UV_ATTRIBUTE_BEGINING_ID 2
#define _NBL_V_IN_COLOR_ATTRIBUTE_BEGINING_ID 5
#define _NBL_V_IN_JOINTS_ATTRIBUTE_BEGINING_ID 8
#define _NBL_V_IN_WEIGHTS_ATTRIBUTE_BEGINING_ID 12

#define _NBL_V_OUT_LOCAL_POSITION_ID 0
#define _NBL_V_OUT_VIEW_POS_ID 1
#define _NBL_V_OUT_UV_ID 2
#define _NBL_V_OUT_COLOR_ID 3

#define _NBL_F_IN_LOCAL_POSITION_ATTRIBUTE_ID 0
#define _NBL_F_IN_VIEW_POS_ATTRIBUTE_ID 1
#define _NBL_F_IN_UV_ATTRIBUTE_ID 2
#define _NBL_F_IN_COLOR_ATTRIBUTE_ID 3

#define _NBL_MAX_UV_ATTRIBUTES 3
#define _NBL_MAX_COLOR_ATTRIBUTES 3
#define _NBL_MAX_JOINTS_ATTRIBUTES 4
#define _NBL_MAX_WEIGHTS_ATTRIBUTES 4