#define _NBL_GLTF_POSITION_ATTRIBUTE_ID 0
#define _NBL_GLTF_UV_ATTRIBUTE_ID 1
#define _NBL_GLTF_COLOR_ATTRIBUTE_ID 2
#define _NBL_GLTF_NORMAL_ATTRIBUTE_ID 3
#define _NBL_GLTF_JOINTS_ATTRIBUTE_ID 4
#define _NBL_GLTF_WEIGHTS_ATTRIBUTE_ID 5

#define _NBL_GLTF_LOCAL_POS_INTERPOLANT 0
#define _NBL_GLTF_UV_INTERPOLANT 1
#define _NBL_GLTF_COLOR_INTERPOLANT 2
#define _NBL_GLTF_NORMAL_INTERPOLANT 3