#version 460 core

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (push_constant) uniform Block
{
	float referenceAlpha;
} pc;

layout (set = 0, binding = 0) uniform sampler2D inImage;
layout (set = 0, binding = 1) restrict buffer coherent Counter
{
	uint data;
} counter;

void main()
{
	const uvec2 textureDim = uvec2(textureSize(inImage, 0));
	if (all(lessThan(gl_GlobalInvocationID.xy, textureDim)))
	{
		const float alpha = texelFetch(inImage, ivec2(gl_GlobalInvocationID.xy), 0).a;

		if (alpha > pc.referenceAlpha)
			atomicAdd(counter.data, 1u);
	}
}