// Copyright (C) 2018-2020 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h

#version 440 core

layout(local_size_x = 2) in;

#include "common.glsl"

void main()
{
	uint uncapped = lineDraw[mdiIndex].count;
	barrier();
	lineDraw[gl_LocalInvocationIndex].count = min(LINE_VERTEX_LIMIT,gl_LocalInvocationIndex!=mdiIndex ? 0u:uncapped);
}