#include <nbl/builtin/hlsl/cpp_compat.hlsl>
#include <nbl/builtin/hlsl/concepts.hlsl>
#include <nbl/builtin/hlsl/fft2/common.hlsl>

#ifdef __HLSL_VERSION

#ifndef _NBL_BUILTIN_HLSL_WORKGROUP2_IMPL_FFT_PRIMARY_ROTATIONS_INCLUDED_
#define _NBL_BUILTIN_HLSL_WORKGROUP2_IMPL_FFT_PRIMARY_ROTATIONS_INCLUDED_

// Works for Radix-2
namespace nbl
{
namespace hlsl
{
namespace workgroup2
{
namespace fft
{
namespace impl
{

template <uint16_t HalfN, uint16_t NumVirtualSubgroupsLog2, typename Scalar>
struct CheaperTwiddlesPrimaryRotation
{
	NBL_CONSTEXPR_STATIC_INLINE complex_t<Scalar> Rotations[NumVirtualSubgroupsLog2];
};

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<3,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<8,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<4,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<8,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_8_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<16,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<5,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<16,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<16,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_16_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<32,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<6,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<32,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<32,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<32,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_32_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<64,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<7,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<64,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<64,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<64,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<64,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_64_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<128,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_128_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_7(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<256,7,SCALAR>::Rotations[7]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_7(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_7(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_7(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_256_7

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_7(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,7,SCALAR>::Rotations[7]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_7(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_7(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_7(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_7

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_8(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<512,8,SCALAR>::Rotations[8]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_8(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_8(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_8(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_512_8

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_7(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,7,SCALAR>::Rotations[7]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_7(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_7(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_7(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_7

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_8(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,8,SCALAR>::Rotations[8]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_8(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_8(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_8(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_8

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_9(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<1024,9,SCALAR>::Rotations[9]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_9(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_9(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_9(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_1024_9

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_7(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,7,SCALAR>::Rotations[7]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_7(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_7(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_7(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_7

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_8(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,8,SCALAR>::Rotations[8]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_8(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_8(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_8(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_8

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_9(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,9,SCALAR>::Rotations[9]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_9(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_9(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_9(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_9

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_10(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<2048,10,SCALAR>::Rotations[10]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_10(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_10(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_10(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_2048_10

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_1(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,1,SCALAR>::Rotations[1]=\
{PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_1(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_1(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_1(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_1

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_2(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,2,SCALAR>::Rotations[2]=\
{PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_2(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_2(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_2(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_2

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_3(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,3,SCALAR>::Rotations[3]=\
{PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_3(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_3(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_3(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_3

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_4(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,4,SCALAR>::Rotations[4]=\
{PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_4(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_4(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_4(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_4

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_5(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,5,SCALAR>::Rotations[5]=\
{PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_5(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_5(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_5(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_5

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_6(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,6,SCALAR>::Rotations[6]=\
{PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_6(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_6(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_6(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_6

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_7(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,7,SCALAR>::Rotations[7]=\
{PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_7(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_7(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_7(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_7

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_8(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,8,SCALAR>::Rotations[8]=\
{PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_8(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_8(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_8(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_8

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_9(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,9,SCALAR>::Rotations[9]=\
{PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_9(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_9(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_9(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_9

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_10(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,10,SCALAR>::Rotations[10]=\
{PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_10(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_10(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_10(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_10

#define CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_11(SCALAR)\
template<> NBL_CONSTEXPR_STATIC_INLINE complex_t<SCALAR>\
CheaperTwiddlesPrimaryRotation<4096,11,SCALAR>::Rotations[11]=\
{PrimitiveRootOfUnity<3,true,SCALAR>,PrimitiveRootOfUnity<4,true,SCALAR>,PrimitiveRootOfUnity<5,true,SCALAR>,PrimitiveRootOfUnity<6,true,SCALAR>,PrimitiveRootOfUnity<7,true,SCALAR>,PrimitiveRootOfUnity<8,true,SCALAR>,PrimitiveRootOfUnity<9,true,SCALAR>,PrimitiveRootOfUnity<10,true,SCALAR>,PrimitiveRootOfUnity<11,true,SCALAR>,PrimitiveRootOfUnity<12,true,SCALAR>,PrimitiveRootOfUnity<13,true,SCALAR>};

CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_11(float16_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_11(float32_t)
CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_11(float64_t)
#undef CHEAPER_TWIDDLES_PRIMARY_ROTATION_4096_11

} //namespace impl
} //namespace fft
} //namespace workgroup2
} //namespace hlsl
} //namespace nbl


#endif
#endif