#version 450

#define _NBL_GLSL_WORKGROUP_SIZE_ (1 << 8)
layout (local_size_x = _NBL_GLSL_WORKGROUP_SIZE_) in;

layout (set = 0, binding = 0, std430) buffer inout_buffer
{
	int inout_values[];
};

#include <nbl/builtin/glsl/workgroup/arithmetic.glsl>
#include <nbl/builtin/glsl/limits/numeric.glsl>


void main()
{
	int data = INT_MAX;
	if (gl_GlobalInvocationID.x < 147)
		data = inout_values[gl_GlobalInvocationID.x];

	int scan_result = nbl_glsl_workgroupExclusiveMin(data);

	if (gl_GlobalInvocationID.x < 147)
		inout_values[gl_GlobalInvocationID.x] = scan_result;
}