#ifndef _IRR_BUILTIN_GLSL_WORKGROUP_SHARED_SHUFFLE_INCLUDED_
#define _IRR_BUILTIN_GLSL_WORKGROUP_SHARED_SHUFFLE_INCLUDED_



#include <irr/builtin/glsl/workgroup/basic.glsl>


#define _IRR_GLSL_WORKGROUP_SHUFFLE_SHARED_SIZE_NEEDED_  _IRR_GLSL_WORKGROUP_SIZE_



#endif
