#ifndef _IRR_BUILTIN_GLSL_WORKGROUP_SHARED_VOTE_INCLUDED_
#define _IRR_BUILTIN_GLSL_WORKGROUP_SHARED_VOTE_INCLUDED_



#include <irr/builtin/glsl/workgroup/basic.glsl>



#define _IRR_GLSL_WORKGROUP_VOTE_SHARED_SIZE_NEEDED_  1



#endif
