switch (swapchainTransform) 
{
case NBL_GLSL_SURFACE_TRANSFORM_E_IDENTITY:
    return ddxDdy;
case NBL_GLSL_SURFACE_TRANSFORM_E_HORIZONTAL_MIRROR:
    return OUTPUT_TYPE(-ddxDdy[0], ddxDdy[1]);
case NBL_GLSL_SURFACE_TRANSFORM_E_HORIZONTAL_MIRROR_ROTATE_180:
    return OUTPUT_TYPE(ddxDdy[0], -ddxDdy[1]);
case NBL_GLSL_SURFACE_TRANSFORM_E_ROTATE_180:
    return OUTPUT_TYPE(-ddxDdy[0], -ddxDdy[1]);
case NBL_GLSL_SURFACE_TRANSFORM_E_ROTATE_90:
    return OUTPUT_TYPE(ddxDdy[1], -ddxDdy[0]);
case NBL_GLSL_SURFACE_TRANSFORM_E_ROTATE_270:
    return OUTPUT_TYPE(-ddxDdy[1], ddxDdy[0]);
case NBL_GLSL_SURFACE_TRANSFORM_E_HORIZONTAL_MIRROR_ROTATE_90:
    return OUTPUT_TYPE(ddxDdy[1], ddxDdy[0]);
case NBL_GLSL_SURFACE_TRANSFORM_E_HORIZONTAL_MIRROR_ROTATE_270:
    return OUTPUT_TYPE(-ddxDdy[1], -ddxDdy[0]);
default:
    return OUTPUT_TYPE(0);
}