#ifndef _NBL_BUILTIN_GLSL_WORKGROUP_SHARED_BLUR_INCLUDED_
#define _NBL_BUILTIN_GLSL_WORKGROUP_SHARED_BLUR_INCLUDED_

#ifndef _NBL_GLSL_EXT_BLUR_AXIS_DIM_
#error "You need to define _NBL_GLSL_EXT_BLUR_AXIS_DIM_!"
#endif

#include <nbl/builtin/glsl/workgroup/shared_arithmetic.glsl>

#if _NBL_GLSL_EXT_BLUR_AXIS_DIM_ < _NBL_GLSL_WORKGROUP_ARITHMETIC_SHARED_SIZE_NEEDED_
    #define _NBL_GLSL_EXT_BLUR_SHARED_SIZE_NEEDED_ _NBL_GLSL_WORKGROUP_ARITHMETIC_SHARED_SIZE_NEEDED_
#else
    #define _NBL_GLSL_EXT_BLUR_SHARED_SIZE_NEEDED_ _NBL_GLSL_EXT_BLUR_AXIS_DIM_
#endif

#endif