#ifndef _NBL_BUILTIN_GLSL_WORKGROUP_SHARED_SHUFFLE_INCLUDED_
#define _NBL_BUILTIN_GLSL_WORKGROUP_SHARED_SHUFFLE_INCLUDED_



#include <nbl/builtin/glsl/workgroup/basic.glsl>


#define _NBL_GLSL_WORKGROUP_SHUFFLE_SHARED_SIZE_NEEDED_  _NBL_GLSL_WORKGROUP_SIZE_



#endif
