// Copyright (C) 2018-2020 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h

#version 450

#pragma shader_stage(compute)

#include "common.h"

layout (local_size_x = 16, local_size_y = 16) in;

layout (push_constant) uniform pushConstants
{
	ShadingPushConstants c;
} u_pushConstants;

layout (set = 0, binding = 0, rg32ui) uniform writeonly uimage2D visbuffer;

void main()
{
	uvec2 coords = gl_GlobalInvocationID.xy;
	if (!all(lessThan(coords, u_pushConstants.c.imgSize)))
	{
		return;
	}
	imageStore(visbuffer, ivec2(coords), uvec4(0.0));
}