// Copyright (C) 2018-2020 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h

#version 450

#pragma shader_stage(compute)

layout (local_size_x = 16, local_size_y = 16) in;

layout (push_constant) uniform pushConstants
{
	uvec2 imgSize;
} u_pushConstants;
layout (set = 0, binding = 0, r32f) uniform readonly image2D visbuffer;

struct WorldPosition {
	float x, y, z;
};

layout (set = 0, binding = 1, std430) readonly buffer pointCloud {
	WorldPosition position[];
} u_pointCloud;

layout (set = 0, binding = 2, rgba8) uniform writeonly image2D outImage;

void main()
{
	uvec2 coords = gl_GlobalInvocationID.xy;
	if (!all(lessThan(coords, u_pushConstants.imgSize)))
	{
		return;
	}
	ivec2 coordsi = ivec2(coords);

	float depth = imageLoad(visbuffer, coordsi).x;
	// Sky pixel
	if (depth == 0.0) {
		imageStore(outImage, coordsi, vec4(0.0));
	} else {
		imageStore(outImage, coordsi, vec4(1.0));
	}
}