find_package(@_NBL_PACKAGE_@
	REQUIRED
	CONFIG
	GLOBAL
	PATHS "${CMAKE_CURRENT_LIST_DIR}/compoment"
	NO_DEFAULT_PATH
	NO_PACKAGE_ROOT_PATH
	NO_CMAKE_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PACKAGE_REGISTRY
	NO_CMAKE_SYSTEM_PATH
	NO_CMAKE_INSTALL_PREFIX
	NO_CMAKE_SYSTEM_PACKAGE_REGISTRY
)