#version 450

#define _NBL_GLSL_WORKGROUP_SIZE_ (1 << 10)

layout (local_size_x = _NBL_GLSL_WORKGROUP_SIZE_) in;

layout (set = 0, binding = 0, std430) buffer inout_buffer
{
	uint inout_values[];
};

layout(push_constant) uniform pushConstants
{
    layout (offset = 0) uint total_element_count;
} u_push_constants;

#include <nbl/builtin/glsl/workgroup/arithmetic.glsl>

void main()
{
	// Todo: no boundary checks, pad instead please
	if (gl_LocalInvocationID.x < u_push_constants.total_element_count)
		inout_values[gl_LocalInvocationID.x] = nbl_glsl_workgroupExclusiveAdd(inout_values[gl_LocalInvocationID.x]);
}