#version 450

#define _NBL_GLSL_WORKGROUP_SIZE_ (1 << 10)

layout (local_size_x = _NBL_GLSL_WORKGROUP_SIZE_) in;

layout (set = 0, binding = 0, std430) readonly buffer h_buffer
{
	uint histogram[];
};

layout (set = 0, binding = 1, std430) writeonly buffer pr_buffer
{
	uint partial_reductions[];
};

layout(push_constant) uniform pushConstants
{
    layout (offset = 0) uint total_element_count;
} u_push_constants;

#include <nbl/builtin/glsl/workgroup/arithmetic.glsl>

void main()
{
	// Todo: Remove boundary checking in favor of padding with identity
	if (gl_GlobalInvocationID.x < u_push_constants.total_element_count)
	{
		uint sum = nbl_glsl_workgroupAdd(histogram[gl_GlobalInvocationID.x]);

		if (gl_LocalInvocationID.x == 0)
			partial_reductions[gl_WorkGroupID.x] = sum;
	}
}