if(NOT DEFINED _NBL_JOBS_AMOUNT_)
	message(WARNING "\"${CMAKE_CURRENT_LIST_FILE}\" included without defined \"_NBL_JOBS_AMOUNT_\", setting it to \"1\"")
	set(_NBL_JOBS_AMOUNT_ 1)
endif()

# notes:
# /arch:sse3 or anything like this is not needed on x64 on MSVC for enabling sse3 instructions

# Debug
set(NBL_C_DEBUG_COMPILE_OPTIONS
	/Ob0 /Od /MP${_NBL_JOBS_AMOUNT_} /fp:fast /Zc:wchar_t /INCREMENTAL
)

if(NBL_SANITIZE_ADDRESS)
	list(APPEND NBL_C_DEBUG_COMPILE_OPTIONS /RTC1)
endif()

set(NBL_CXX_DEBUG_COMPILE_OPTIONS
	/Zc:__cplusplus ${NBL_C_DEBUG_COMPILE_OPTIONS}
)

set(NBL_DEBUG_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_DEBUG_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_DEBUG_COMPILE_OPTIONS}>
)

# Release
set(NBL_C_RELEASE_COMPILE_OPTIONS
	/O2 /Ob2 /DNDEBUG /GL /MP${_NBL_JOBS_AMOUNT_} /Gy- /Zc:wchar_t /sdl- /GF /GS- /fp:fast
)
set(NBL_CXX_RELEASE_COMPILE_OPTIONS
	/Zc:__cplusplus ${NBL_C_RELEASE_COMPILE_OPTIONS}
)

set(NBL_RELEASE_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_RELEASE_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_RELEASE_COMPILE_OPTIONS}>
)

# RelWithDebInfo
set(NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS
	/O2 /Ob1 /DNDEBUG /GL /Zc:wchar_t /MP${_NBL_JOBS_AMOUNT_} /Gy /sdl- /Oy- /fp:fast
)
set(NBL_CXX_RELWITHDEBINFO_COMPILE_OPTIONS
	/Zc:__cplusplus ${NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS}
)

set(NBL_RELWITHDEBINFO_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_RELWITHDEBINFO_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS}>
)

# Global
unset(NBL_C_COMPILE_OPTIONS)
unset(NBL_CXX_COMPILE_OPTIONS)

if(NBL_SANITIZE_ADDRESS)
	list(APPEND NBL_C_COMPILE_OPTIONS /fsanitize=address)
	list(APPEND NBL_CXX_COMPILE_OPTIONS ${NBL_C_COMPILE_OPTIONS})
endif()

set(NBL_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_COMPILE_OPTIONS}>
)

# this should also be not part of profile, pasting from old flags-set function temporary
# TODO: use profile

#reason for INCREMENTAL:NO: https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=vs-2019 /LTCG is not valid for use with /INCREMENTAL.
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} /INCREMENTAL:NO /LTCG:incremental")