#version 430 core

#include "common.glsl"

layout(local_size_x = kOptimalWorkgroupSize) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer WorldParams
{
    uint drawData[];
} world;
layout(set = 0, binding = 1, std430) restrict writeonly buffer CameraParams
{
    uint drawData[];
} camera;

layout(push_constant, row_major) uniform PushConstants
{
    uint drawDataArrayDWORDSize;
} pc;

void main()
{
    uint dword = gl_GlobalInvocationID.x;
    if (dword<drawDataArrayDWORDSize)
        camera.drawData[dword] = world.drawData[dword];
}
