// Copyright (C) 2018-2020 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h
#version 430 core
#define G_IDX gl_GlobalInvocationID.x
#define G_IDY gl_GlobalInvocationID.y
#define LC_IDX gl_LocalInvocationIndex


layout(local_size_x = 10) in;


layout(std430, binding = 0) buffer InBuf {
	int input[];
};

//shared Temp[1024];

// float count_occurencies(int input)
// {
//     return 1.0;
// }

void main()
{
    input[gl_GlobalInvocationID.x] = 10;
}