// Copyright (C) 2023 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h
#ifndef _NBL_BUILTIN_HLSL_TEXT_RENDERING_MSDF_INCLUDED_
#define _NBL_BUILTIN_HLSL_TEXT_RENDERING_MSDF_INCLUDED_

namespace nbl 
{
namespace hlsl
{
namespace text
{

float median(float r, float g, float b) {
    return max(min(r, g), min(max(r, g), b));
}

// Returns the distance to the shape in the given MSDF.
// This can then be processed using smoothstep to provide anti-alising
// when rendering the shape.
//
// - msd is the sampled texture of the MSDF as generated by MSDFgen.
// - msdfPixelRange is how many pixels away from the shape the signed distance field
// has distance for it (for example, if msdfPixelRange is 4, then a value of 0.5 means
// the sample is 2 pixels away from the shape, since 0.5 * 4 = 2). This value is set
// when rendering the MSDF with MSDFgen.
// - screenPxRangeValue is the screen-space size of the shape divided by the resolution of
// the MSDF texture.
float msdfDistance(float3 msd, float msdfPixelRange, float screenPxRangeValue) {
    float snormSignedDistance = (median(msd.r, msd.g, msd.b) - 0.5) * 2.0;
    return screenPxRangeValue * msdfPixelRange * snormSignedDistance;
}

}
}
}

#endif
