// Copyright (C) 2023-2024 - DevSH Graphics Programming Sp. z O.O.
// This file is part of the "Nabla Engine".
// For conditions of distribution and use, see copyright notice in nabla.h
#undef NBL_CONCEPT_PARAM_31
#undef NBL_CONCEPT_PARAM_30
#undef NBL_CONCEPT_PARAM_29
#undef NBL_CONCEPT_PARAM_28
#undef NBL_CONCEPT_PARAM_27
#undef NBL_CONCEPT_PARAM_26
#undef NBL_CONCEPT_PARAM_25
#undef NBL_CONCEPT_PARAM_24
#undef NBL_CONCEPT_PARAM_23
#undef NBL_CONCEPT_PARAM_22
#undef NBL_CONCEPT_PARAM_21
#undef NBL_CONCEPT_PARAM_20
#undef NBL_CONCEPT_PARAM_19
#undef NBL_CONCEPT_PARAM_18
#undef NBL_CONCEPT_PARAM_17
#undef NBL_CONCEPT_PARAM_16
#undef NBL_CONCEPT_PARAM_15
#undef NBL_CONCEPT_PARAM_14
#undef NBL_CONCEPT_PARAM_13
#undef NBL_CONCEPT_PARAM_12
#undef NBL_CONCEPT_PARAM_11
#undef NBL_CONCEPT_PARAM_10
#undef NBL_CONCEPT_PARAM_9
#undef NBL_CONCEPT_PARAM_8
#undef NBL_CONCEPT_PARAM_7
#undef NBL_CONCEPT_PARAM_6
#undef NBL_CONCEPT_PARAM_5
#undef NBL_CONCEPT_PARAM_4
#undef NBL_CONCEPT_PARAM_3
#undef NBL_CONCEPT_PARAM_2
#undef NBL_CONCEPT_PARAM_1
#undef NBL_CONCEPT_PARAM_0
#undef NBL_CONCEPT_TPLT_PRM_NAMES
#undef NBL_CONCEPT_TPLT_PRM_KINDS
#undef NBL_CONCEPT_NAME