#version 450

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupExclusiveMax(sourceVal);
	nbl_glsl_workgroupBallot((sourceVal&0x1u)==0x1u);
	bitCountOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupBallotExclusiveBitCount();

}