#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupInclusiveMax(sourceVal);
}