#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "common.glsl"

void main()
{
	andOutput [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveAnd(inputValue[gl_LocalInvocationIndex]);
	xorOutput [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveXor(inputValue[gl_LocalInvocationIndex]);
	orOutput  [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveOr (inputValue[gl_LocalInvocationIndex]);
	addOutput [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveAdd(inputValue[gl_LocalInvocationIndex]);
	multOutput[gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveMul(inputValue[gl_LocalInvocationIndex]);
	minOutput [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveMin(inputValue[gl_LocalInvocationIndex]);
	maxOutput [gl_LocalInvocationIndex] = irr_glsl_subgroupInclusiveMax(inputValue[gl_LocalInvocationIndex]);
}
