#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "subgroupCommon.glsl"

void main()
{
	CONDITIONAL_CLEAR_HEAD
	CONDITIONAL_CLEAR_AND
	andOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveAnd(sourceVal);
	CONDITIONAL_CLEAR_OR_XOR_ADD
	xorOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveXor(sourceVal);
	CONDITIONAL_CLEAR_OR_XOR_ADD
	orOutput  [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveOr (sourceVal);
	CONDITIONAL_CLEAR_OR_XOR_ADD
	addOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveAdd(sourceVal);
	CONDITIONAL_CLEAR_MUL
	multOutput[gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveMul(sourceVal);
	CONDITIONAL_CLEAR_MIN
	minOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveMin(sourceVal);
	CONDITIONAL_CLEAR_MAX
	maxOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupInclusiveMax(sourceVal);
}