#version 450

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupInclusiveMax(sourceVal);
	nbl_glsl_workgroupBallot((sourceVal&0x1u)==0x1u);
	bitCountOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupBallotInclusiveBitCount();
}