#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "common.glsl"

void main()
{
	if(gl_GlobalInvocationID.x < MAX_BUFFER_INDEX)
	{
		andOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupAnd(inputValue[gl_GlobalInvocationID.x]);
		xorOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupXor(inputValue[gl_GlobalInvocationID.x]);
		orOutput  [gl_GlobalInvocationID.x] = irr_glsl_subgroupOr (inputValue[gl_GlobalInvocationID.x]);
		addOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupAdd(inputValue[gl_GlobalInvocationID.x]);
		multOutput[gl_GlobalInvocationID.x] = irr_glsl_subgroupMul(inputValue[gl_GlobalInvocationID.x]);
		minOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupMin(inputValue[gl_GlobalInvocationID.x]);
		maxOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupMax(inputValue[gl_GlobalInvocationID.x]);
	}
}
