#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "shaderCommon.glsl"

void main()
{
	CONDITIONAL_CLEAR_AND
	andOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveAnd(inputValue[gl_GlobalInvocationID.x]);
	CONDITIONAL_CLEAR_OR_XOR_ADD
	xorOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveXor(inputValue[gl_GlobalInvocationID.x]);
	orOutput  [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveOr (inputValue[gl_GlobalInvocationID.x]);
	addOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveAdd(inputValue[gl_GlobalInvocationID.x]);
	CONDITIONAL_CLEAR_MUL
	multOutput[gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveMul(inputValue[gl_GlobalInvocationID.x]);
	CONDITIONAL_CLEAR_MIN
	minOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveMin(inputValue[gl_GlobalInvocationID.x]);
	CONDITIONAL_CLEAR_MAX
	maxOutput [gl_GlobalInvocationID.x] = irr_glsl_subgroupExclusiveMax(inputValue[gl_GlobalInvocationID.x]);
}