#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = irr_glsl_workgroupOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = irr_glsl_workgroupMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupMax(sourceVal);
}
