#version 450

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = nbl_glsl_workgroupOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = nbl_glsl_workgroupMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupMax(sourceVal);
	nbl_glsl_workgroupBallot((sourceVal&0x1u)==0x1u);
	bitCountOutput [gl_GlobalInvocationID.x] = nbl_glsl_workgroupBallotBitCount();

}
