#version 450
#define _IRR_GLSL_WORKGROUP_SIZE_ ???? 

#include "workgroupCommon.glsl"

void main()
{
	const uint sourceVal = inputValue[gl_GlobalInvocationID.x];
	andOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveAnd(sourceVal);
	xorOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveXor(sourceVal);
	orOutput  [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveOr (sourceVal);
	addOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveAdd(sourceVal);
	multOutput[gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveMul(sourceVal);
	minOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveMin(sourceVal);
	maxOutput [gl_GlobalInvocationID.x] = irr_glsl_workgroupExclusiveMax(sourceVal);
}