#include "nbl/builtin/glsl/ext/Scan/default_sweep_common.glsl"

#ifndef _NBL_GLSL_EXT_SCAN_DOWNSWEEP_TYPE_
#error "_NBL_GLSL_EXT_SCAN_DOWNSWEEP_TYPE_ is not defined! Recheck _NBL_GLSL_EXT_SCAN_BIN_OP_!"
#endif

#include "nbl/builtin/glsl/ext/Scan/scan.glsl"

#ifndef _NBL_GLSL_EXT_SCAN_DOWNSWEEP_MAIN_DEFINED_

void main()
{
	uint idx = min(nbl_glsl_ext_Scan_Parameters_t_getElementCountTotal() - 1u,
		(gl_GlobalInvocationID.x + 1u) * nbl_glsl_ext_Scan_Parameters_t_getStride() - 1u);
	nbl_glsl_ext_Scan_Storage_t result;
	_NBL_GLSL_EXT_SCAN_DOWNSWEEP_TYPE_(idx, result);
	nbl_glsl_ext_Scan_setData(idx, result);
}

#define _NBL_GLSL_EXT_SCAN_DOWNSWEEP_MAIN_DEFINED_
#endif