#include "nbl/builtin/glsl/ext/Scan/default_sweep_common.glsl"

#ifndef _NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_
#error "_NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_ must be defined! Recheck _NBL_GLSL_EXT_SCAN_BIN_OP_!"
#endif

#include "nbl/builtin/glsl/ext/Scan/scan.glsl"

#ifndef _NBL_GLSL_EXT_SCAN_UPSWEEP_MAIN_DEFINED_

void main()
{
	uint idx = min(nbl_glsl_ext_Scan_Parameters_t_getElementCountTotal() - 1u,
		(gl_GlobalInvocationID.x + 1u) * nbl_glsl_ext_Scan_Parameters_t_getStride() - 1u);
	uint result = _NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_(idx);
	nbl_glsl_ext_Scan_setData(idx, result);
}

#define _NBL_GLSL_EXT_SCAN_UPSWEEP_MAIN_DEFINED_
#endif