#include "nbl/builtin/glsl/ext/Scan/default_sweep_common.glsl"

#ifndef _NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_
#error "_NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_ must be defined! Recheck _NBL_GLSL_EXT_SCAN_BIN_OP_!"
#endif

#ifndef _NBL_GLSL_EXT_SCAN_GET_PADDED_DATA_DEFINED_

nbl_glsl_ext_Scan_Storage_t nbl_glsl_ext_Scan_getPaddedData(in uint idx, in nbl_glsl_ext_Scan_Storage_t pad_val)
{
	nbl_glsl_ext_Scan_Storage_t data = pad_val;
	if (gl_GlobalInvocationID.x < nbl_glsl_ext_Scan_Parameters_t_getElementCountPass())
		data = inout_values[idx];

	return data;
}

#define _NBL_GLSL_EXT_SCAN_GET_PADDED_DATA_DEFINED_
#endif

#include "nbl/builtin/glsl/ext/Scan/scan.glsl"

void nbl_glsl_ext_Scan_defaultUpsweep()
{
	uint idx = min(nbl_glsl_ext_Scan_Parameters_t_getElementCountTotal() - 1u, (gl_GlobalInvocationID.x + 1u) * nbl_glsl_ext_Scan_Parameters_t_getStride() - 1u);
	nbl_glsl_ext_Scan_Storage_t result;
	_NBL_GLSL_EXT_SCAN_UPSWEEP_TYPE_(idx, result);
	nbl_glsl_ext_Scan_setData(idx, result);
}

#ifndef _NBL_GLSL_EXT_SCAN_UPSWEEP_MAIN_DEFINED_

void main()
{
	nbl_glsl_ext_Scan_defaultUpsweep();
}

#define _NBL_GLSL_EXT_SCAN_UPSWEEP_MAIN_DEFINED_
#endif