#version 440 core
layout(local_size_x=_NBL_GLSL_WORKGROUP_SIZE_) in;


#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_LIST_DESCRIPTOR_BINDING
#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_DRAWCALL_OFFSETS_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_DRAWCALL_EXCLUSIVE_COUNTS_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_PVS_INSTANCE_DRAWS_DESCRIPTOR_QUALIFIERS restrict writeonly
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAWCALLS_TO_SCAN_DESCRIPTOR_BINDING
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_COUNTS_TO_SCAN_DESCRIPTOR_BINDING
#include <nbl/builtin/glsl/culling_lod_selection/input_descriptor_set.glsl>

#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_CALLS_DESCRIPTOR_QUALIFIERS restrict coherent
#define NBL_GLSL_CULLING_LOD_SELECTION_PER_VIEW_PER_INSTANCE_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_PER_INSTANCE_REDIRECT_ATTRS_DESCRIPTOR_BINDING
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_CALL_COUNTS_DESCRIPTOR_BINDING
#include <nbl/builtin/glsl/culling_lod_selection/output_descriptor_modifiers.glsl>


void main()
{
    const uint drawInstanceCount = lodDrawcallExclusiveCounts.data[lodDrawcallExclusiveCounts.count-1u];
    for (uint drawInstanceIndex=gl_GlobalInvocationID.x; drawInstanceIndex<drawInstanceCount; drawInstanceIndex+=_NBL_GLSL_WORKGROUP_SIZE_)
    {
    #if 0
        // upper_bound in lodDrawcallExclusiveCounts.data
        const uint pvInstanceID = upper_bound(drawInstanceIndex)-1u;
        const uint drawCallDWORDOffsetAddr = lodDrawcallOffsets.data[pvInstanceID]+(drawInstanceIndex-lodDrawcallExclusiveCounts.data[pvInstanceID]);
        const uint drawCallDWORDOffset = lodInfos.data[drawCallDWORDOffsetAddr];
        // get AABB
        const nbl_glsl_AABB_t aabb = ;
        // cull
        bool visible = true;
        if (visible)
        {
            const uint appendIx = atomicAdd(dispatchIndirect.potentiallyVisibleDrawInstanceCount,1u);
            uint instanceID = nbl_glsl_culling_lod_selection_drawCallInstanceCountIncr(drawDWORDOffset);

            const uint baseInstanceDWORDOffset = drawDWORDOffset+4u;
            unsortedDrawInstances.data[appendIx] = uvec4(baseInstanceDWORDOffset,instanceID,instanceGUID,perViewPerInstanceID);
            nbl_glsl_culling_lod_selection_drawCallSetDWORD(baseInstanceDWORDOffset,0u);
        }
    #endif
    }
}