#version 440 core
layout(local_size_x=_NBL_GLSL_WORKGROUP_SIZE_) in;

#include <nbl/builtin/glsl/lod_library/descriptor_set.glsl>
#include <nbl/builtin/glsl/lod_library/structs.glsl>

#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_LIST_DESCRIPTOR_DECLARED
#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_PVS_INSTANCES_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_INSTANCE_DRAWCALL_INCLUSIVE_COUNTS_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_PVS_INSTANCE_DRAWS_DESCRIPTOR_QUALIFIERS restrict
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAWCALLS_TO_SCAN_DESCRIPTOR_DECLARED
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_COUNTS_TO_SCAN_DESCRIPTOR_DECLARED
// dont pull the scan scratch descriptor (we'll use our own decl for clearing)
#define _NBL_GLSL_SCAN_DESCRIPTORS_INCLUDED_
#include <nbl/builtin/glsl/culling_lod_selection/input_descriptor_set.glsl>
layout(set=_NBL_GLSL_SCAN_DESCRIPTOR_SET_DEFINED_,binding=_NBL_GLSL_SCAN_SCRATCH_BINDING_DEFINED_) restrict writeonly buffer ScanScratchBuffer
{
    uint data[];
} scanScratch;

#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_CALLS_DESCRIPTOR_QUALIFIERS restrict coherent
#define NBL_GLSL_CULLING_LOD_SELECTION_PER_VIEW_PER_INSTANCE_DESCRIPTOR_QUALIFIERS restrict readonly
#define NBL_GLSL_CULLING_LOD_SELECTION_PER_INSTANCE_REDIRECT_ATTRS_DESCRIPTOR_DECLARED
#define NBL_GLSL_CULLING_LOD_SELECTION_DRAW_CALL_COUNTS_DESCRIPTOR_DECLARED
#include <nbl/builtin/glsl/culling_lod_selection/output_descriptor_modifiers.glsl>

#include <nbl/builtin/glsl/algorithm.glsl>
NBL_GLSL_DEFINE_UPPER_BOUND(lodDrawcallInclusiveCounts,uint)

layout(push_constant) uniform PushConstants
{
    uint lastScratchDWORDToClear;
} pc;

void main()
{
    if (gl_GlobalInvocationID.x==0u)
        dispatchIndirect.instanceDrawCountPrefixSum.num_groups_x = 1u;
    
    for (uint dword=gl_GlobalInvocationID.x; dword<=pc.lastScratchDWORDToClear; dword+=_NBL_GLSL_WORKGROUP_SIZE_)
        scanScratch.data[dword] = 0u;
        
    const uint totalInstanceCount = totalInstanceCountAfterCull;
    const uint drawInstanceCount = lodDrawcallInclusiveCounts[totalInstanceCount-1u];
    for (uint drawInstanceIndex=gl_GlobalInvocationID.x; drawInstanceIndex<drawInstanceCount; drawInstanceIndex+=_NBL_GLSL_WORKGROUP_SIZE_)
    {
        // TODO: implement via https://moderngpu.github.io/sortedsearch.html, find the upper and lower bounds of the workgroup, then go to town with sorted search
        const uint pvInstanceID = upper_bound_lodDrawcallInclusiveCounts_NBL_GLSL_LESS(0u,totalInstanceCount,drawInstanceIndex);
        const uint lodInfoUvec4Offset = pvsInstances.data[pvInstanceID][1];

        uint drawInstanceID = drawInstanceIndex;
        if (bool(pvInstanceID))
            drawInstanceID -= lodDrawcallInclusiveCounts[pvInstanceID-1u];

        const uint drawcallDWORDOffsetAndFlag = nbl_glsl_lod_library_DefaultInfo_getDrawCallDWORDOffset(lodInfoUvec4Offset,drawInstanceID);
        // get AABB
        //const nbl_glsl_AABB_t aabb = Draw_getAABB();
        // cull
        bool visible = true;
        if (visible)
        {
            const uint appendIx = atomicAdd(pvsInstanceDraws.count,1u);
            const uint drawcallDWORDOffset = drawcallDWORDOffsetAndFlag&0x7fffffffu;
            const uint instanceID = nbl_glsl_culling_lod_selection_drawCallInstanceCountIncr(drawcallDWORDOffset);
            
            const uint baseInstanceDWORDOffset = drawcallDWORDOffset+4u-(drawcallDWORDOffsetAndFlag>>31);

            pvsInstanceDraws.data[appendIx].perViewPerInstanceID = pvInstanceID;
            pvsInstanceDraws.data[appendIx].drawBaseInstanceDWORDOffset = baseInstanceDWORDOffset;
            pvsInstanceDraws.data[appendIx].instanceID = instanceID;
        }
    }
}