#version 430 core
#define G_IDX gl_GlobalInvocationID.x
layout(local_size_x = 256) in;

layout(std430, binding = 0) restrict readonly buffer InBuf {
	uint input[];
};
layout(std430, binding = 1) restrict writeonly buffer OutBuf {
	uint output[];
};

void main()
{
	const uint mask = 0xffff;
	const uint idx = input[G_IDX];
	const uint i0 = idx & mask;
	const uint i1 = (idx>>16) & mask;
	
	output[2*G_IDX] = i0;
	output[2*G_IDX+1] = i1;
}