#ifndef _NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET_GLSL_INCLUDED_
#define _NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET_GLSL_INCLUDED_


#ifndef NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET
#define NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET 0
#endif

#ifndef NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_BINDING
#define NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_BINDING 0
#ifndef NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_QUALIFIERS
#define NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_QUALIFIERS readonly restrict
#endif
layout(
    set=NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET,
    binding=NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_BINDING
) NBL_GLSL_LOD_LIBRARY_LOD_TABLES_DESCRIPTOR_QUALIFIERS buffer LodTables
{
    uvec4 data[];
} lodTables;
#endif

#ifndef NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_BINDING
#define NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_BINDING 1
#ifndef NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_QUALIFIERS
#define NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_QUALIFIERS readonly restrict
#endif
layout(
    set=NBL_GLSL_LOD_LIBRARY_DESCRIPTOR_SET,
    binding=NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_BINDING
) NBL_GLSL_LOD_LIBRARY_LOD_INFOS_DESCRIPTOR_QUALIFIERS buffer LodInfos
{
    uint data[];
} lodInfos;

uint nbl_glsl_lod_library_getDrawCallDWORDOffset(in uint lodInfoUvec4Offset, in uint offsetofDWORDFirstDrawcallInfo, in uint drawcallID)
{
    return lodInfos.data[(lodInfoUvec4Offset<<2u)+offsetofDWORDFirstDrawcallInfo+(drawcallID<<1u)];
}
#endif


#endif