if(NOT TARGET ZLIB::ZLIB)
	message(FATAL_ERROR "define ZLIB::ZLIB target!")
endif()

set(ZLIB_FOUND TRUE)
set(ZLIB_LIBRARY ZLIB::ZLIB)
set(ZLIB_INCLUDE_DIR "${THIRD_PARTY_SOURCE_DIR}/zlib;${THIRD_PARTY_BINARY_DIR}/zlib")