include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")

# Debug
list(APPEND NBL_C_DEBUG_COMPILE_OPTIONS
	-glldb
)
list(APPEND NBL_CXX_DEBUG_COMPILE_OPTIONS
	${NBL_C_DEBUG_COMPILE_OPTIONS}
)

set(NBL_DEBUG_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_DEBUG_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_DEBUG_COMPILE_OPTIONS}>
)

# Release
list(APPEND NBL_C_RELEASE_COMPILE_OPTIONS
	-fexpensive-optimizations
)
list(APPEND NBL_CXX_RELEASE_COMPILE_OPTIONS
	${NBL_C_RELEASE_COMPILE_OPTIONS}
)

set(NBL_RELEASE_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_RELEASE_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_RELEASE_COMPILE_OPTIONS}>
)

# RelWithDebInfo
list(APPEND NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS
	# empty
)
list(APPEND NBL_CXX_RELWITHDEBINFO_COMPILE_OPTIONS
	${NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS}
)

set(NBL_RELWITHDEBINFO_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_RELWITHDEBINFO_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_RELWITHDEBINFO_COMPILE_OPTIONS}>
)

# Global
list(APPEND NBL_C_COMPILE_OPTIONS 
	# empty
)

list(APPEND NBL_CXX_COMPILE_OPTIONS ${NBL_C_COMPILE_OPTIONS})

set(NBL_COMPILE_OPTIONS
	$<$<COMPILE_LANGUAGE:CXX>:${NBL_CXX_COMPILE_OPTIONS}>
	$<$<COMPILE_LANGUAGE:C>:${NBL_C_COMPILE_OPTIONS}>
)

# okay this thing is bad and needs an adjustment, for keeping it work I will leave it temporary here
# TODO: use profile above to make config map working, do not force cache
function(NBL_INSERT_ANDROID_FLAGS _NBL_CMAKE_FLAGS_VARIABLE_NAME_)
	string(FIND "${${_NBL_CMAKE_FLAGS_VARIABLE_NAME_}}" "-g -glldb" CHECK)
	if(${CHECK} EQUAL -1)
		set(${_NBL_CMAKE_FLAGS_VARIABLE_NAME_} "${${_NBL_CMAKE_FLAGS_VARIABLE_NAME_}} -g -glldb" CACHE STRING "" FORCE)
	endif()
endfunction()

NBL_INSERT_ANDROID_FLAGS(CMAKE_ASM_FLAGS_DEBUG)
NBL_INSERT_ANDROID_FLAGS(CMAKE_CXX_FLAGS_DEBUG)
NBL_INSERT_ANDROID_FLAGS(CMAKE_C_FLAGS_DEBUG)
NBL_INSERT_ANDROID_FLAGS(CMAKE_EXE_LINKER_FLAGS_DEBUG)
NBL_INSERT_ANDROID_FLAGS(CMAKE_MODULE_LINKER_FLAGS_DEBUG)
NBL_INSERT_ANDROID_FLAGS(CMAKE_SHARED_LINKER_FLAGS_DEBUG)