#version 460 core

#extension GL_EXT_shader_16bit_storage : require

#include "cullShaderCommon.h"
layout(local_size_x = WORKGROUP_SIZE) in;

#define OCCLUSION_CULLED_COMMAND_BUFF_SET 0
#define OCCLUSION_CULLED_COMMAND_BUFF_BINDING 0
#define VISIBLE_BUFF_SET 0
#define VISIBLE_BUFF_BINDING 1
#define CUBE_DRAW_GUID_BUFF_SET 0
#define CUBE_DRAW_GUID_BUFF_BINDING 2
#define CUBE_COMMAND_BUFF_SET 0
#define CUBE_COMMAND_BUFF_BINDING 3
#include "occlusionCullingShaderCommon.glsl"

void main()
{
    if(gl_GlobalInvocationID.x > cubeIndirectDraw.draw.instanceCount)
        return;

    if(uint(visibleBuff.visible[gl_GlobalInvocationID.x]) == 0)
        return;
    
    const uint batchMdiOffset = cubeDrawGUIDBuffer.drawGUID[gl_GlobalInvocationID.x];
    occlusionCommandBuff.draws[batchMdiOffset].instanceCount = 1;
    
    visibleBuff.visible[gl_GlobalInvocationID.x] = uint16_t(0u);
}